### PR TITLE
Add Postcss, remove < ie 8 hacks and other fixes

### PR DESCRIPTION
**Pull request by redonkulus**
@ericf @lkraav @absalomedia

Proper attribution for the work goes to @lkraav and @absalomedia respectively.

This PR replaces https://github.com/yahoo/pure/pull/615 and https://github.com/yahoo/pure/pull/551. I did this to test it out locally and remove the bower changes that were included in those PRs. The output looks fine locally. I validated the output from postcss against what was there before. 

Fixes: #575, #576, #351, #377, #381, #447, #480, #547, #539, #550, #583

### Need to test the following Browsers
- [ ] IE8
- [ ] IE9
- [ ] IE10
- [ ] IE11
- [ ] Chrome
- [ ] Firefox
- [ ] iOS Safari
- [ ] Android 4+

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by absalomedia** [comment]
Just a quick thing.  There's still a PR dependency inside Rework Pure Grids to fully close #575 & #576. This current PR you created covers everything except a fully optimized Pure Grid generation.

**Comment by redonkulus** [comment]
@absalomedia @lkraav I'm usually not in favor or PR's like this do too many things and make it harder to revert if issues come up. So I'd prefer to break up the various fixes into separate PR's. I will try to merge any of the original PR's that were minor bug fixes by users. 

As for dropping < IE 8 support, I prefer to keep that as a separate task for the new maintainers. Its a fairly big change; not code wise, but project philosphy wise. I would prefer the next maintainers to evaluate if they want to do this and then help support the community if they choose to go forward.

**Comment by redonkulus** [comment]
Closing in favor of https://github.com/yahoo/pure/pull/617

**Comment by lkraav** [comment]
I'm all for small piecework, but was thinking here that you were going to cherry-pick+amend the commits instead of an outright merge.

**Comment by redonkulus** [comment]
@lkraav I can do that too, so you get the commit credit, I didn't really add anything more to what you already did. I can fix it in the new PR I created.

**Pull request closed without merging**
