### PR TITLE
Adds 7th's based grid

### PR DESCRIPTION
**Pull request by arnoldsandoval**
Based on up for grabs feature request: https://github.com/yahoo/pure/issues/455

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by arnoldsandoval** [comment]
Done!

**Comment by redonkulus** [comment]
@arnoldsandoval is this still wanted or needed?

**Comment by yahoocla** [comment]
CLA is valid!

**Pull request closed without merging**
