### PR TITLE
Update LICENSE.md

### PR DESCRIPTION
**Pull request by masteradhoc**
Copyright to 2015

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by masteradhoc** [comment]
Good to see you, Brian

You previously signed this CLA on:
Fri May 22 2015 09:32:12 GMT+0000 (UTC)

**Comment by paazmaya** [comment]
Soon it will be 2016, by the time that the CLA bot responds....

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by paazmaya** [comment]
Thank you @yahoocla !

**Comment by gyehuda** [comment]
Open Source projects do not need to update their copyright dates every year. 

The point of the year in a copyright statement is to "start the clock" to determine when copyright protection runs out. For this type of work, US law protects it for 95 years from the first publication or 120 years from the date of its creation, whichever is less. Meaning that in 93 years from now, this project will transition from "open source licensed" to "public domain." If we update the date, then we are asking for protection for another year or two (and that protection would probably only apply to the new code anyway). We do not seek to get that extra year of protection in the 22nd century. Why? 1. We open sourced this since we want people to use it and are not looking for a lot of copyright protection (aside from ensuring the open source license is enforced). and 2. We hope that in 94 years from now someone will have created an even better version of Pure CSS that our great grandchildren will use.

So we are OK keeping the copyright date to be the date of publication, and only updating it if we make substantial changes or when we add new files. In the case of new files, kindly use the current year of publication in the copyright line.

**Comment by redonkulus** [comment]
Thanks @gyehuda, great answer. I will close this then.

**Pull request closed without merging**
