### PR TITLE
Remove duplicate Firefox inner focus border

### PR DESCRIPTION
**Pull request by diegoleme**
Snippet already exists in https://github.com/yahoo/pure/blob/master/src/buttons/css/buttons-core.css#L20

```
  &::-moz-focus-inner {
    padding: 0;
    border: 0;
  }
```

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by diegoleme** [comment]
I agree the term!

**Comment by jamesalley** [comment]
Sorry about the CLA issue, we have been working with GitHub to resolve the problem.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
LGTM

**Comment by redonkulus** [comment]
@diegoleme released in 0.6.1

**Pull request merged**
