### PR TITLE
Migrate to post-css for browser prefixes

### PR DESCRIPTION
**Pull request by redonkulus**
@lkraav @absalomedia

This replaces the per browser prefixes by using PostCSS to generate them at build time. Replaces or fixes the issues below.

Fixes: #351, #377, #447, #547, #550

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
@lkraav updated to include your commits now

**Comment by lkraav** [comment]
Yey. What's the next step now?

**Comment by redonkulus** [comment]
Verify, merge then release. I've checked the build files, they look fine. Just need to check the examples in some browsers. Should be done early this week.

**Comment by redonkulus** [comment]
@lkraav @absalomedia released in 0.6.1

**Pull request merged**
