### PR TITLE
composer file

### PR DESCRIPTION
**Pull request by agentcobra**
add composer.json file for installation with composer and maybe later add pure in [packagist.org](http://packagist.org)

### CODE REVIEW

**Comment by redonkulus** [comment]
@agentcobra seems pretty bare. How does this help in composer?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by lkraav** [comment]
Multiple prominent projects have decided against trying to support all packaging ecosystems directly. NPM usually wins, everybody else simply has to do direct git tags, and mostly that works out fine.

But not sure yet which way we're going to go here. Less busywork is better, though.

**Comment by redonkulus** [comment]
Closing this to standardize on NPM instead of more package managers. We plan to deprecate Bower too.

**Pull request closed without merging**
