### PR TITLE
Add composer.json file

### LINKED ISSUE #623: Enhancement request: Composer support
### Description

Would be nice if Pure supported being retrieved as a Composer package from Packagist, similar to other common web resources, such as jQuery.

### PR DESCRIPTION
**Pull request by redonkulus**
Fixes #623 #594 

Makes it easy for the PHP community to consume Pure.

/cc @cxj @chewett

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
Also submitted to Packagist https://packagist.org/packages/yahoo/purecss

**Comment by chewett** [comment]
Cheers!

**Comment by cxj** [comment]
Thanks much!

**Pull request merged**
