### PR TITLE
Adds LESS files

### PR DESCRIPTION
**Pull request by marcsoler**
LESSifies the CSS for easy customization. Includes variable file.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by TCattd** [comment]
Nice :+1:

**Comment by jwogrady** [comment]
....and sass....:-)

**Comment by jvincilione** [comment]
Any update on when this will be merged?

**Comment by jayasurian123** [comment]
Is this library is getting updated sometime?
I have seen the last merge was around 1 year back!

**Comment by redonkulus** [comment]
This PR is unlikely to be merged, as we do not have plans to support LESS as well. 

> Is this library is getting updated sometime?
> I have seen the last merge was around 1 year back!

See https://github.com/yahoo/pure/issues/414#issuecomment-132315132 for more info.

**Comment by spartanatreyu** [comment]
@jayasurian123 @redonkulus 

> [There will be new maintenership news in April and things will start moving again.](https://github.com/yahoo/pure/issues/557#issuecomment-194221850)

Here's hoping for some sass for basic customisation for themes

**Pull request closed without merging**
