### PR TITLE
Style tfoot elements the same as thead elements.

### PR DESCRIPTION
**Pull request by dpassen1**
Test table is a bit odd, but extending the style seems useful.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by dpassen1** [comment]
Accepted CLA terms.

**Comment by redonkulus** [comment]
Not sure how I feel about this, does the footer need to have the same treatment as the header? Can you share a screen shot with change? In some instances perhaps its better for the footer to be left unstyled.

@lkraav for thoughts.

**Pull request closed without merging**
