### PR TITLE
Fixing initial copyright year

### PR DESCRIPTION
**Pull request by pra85**
According to http://www.copyright.gov/circs/circ01.pdf , document should list its first year of publication in its copyright

### CODE REVIEW

**Comment by okuryu** [comment]
Try to check https://github.com/yahoo/pure/pull/493#issuecomment-161398205.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by pra85** [comment]
@okuryu Thanks for the link to that issue. I have updated the pull request to remove the range to the current year. Now it only contains the initial copyright right year (i.e. is 2013)

The commit 82b16cf9534f638a9e01b changed the initial copyright year from 2013 to 2014

This will revert it back to 2013 , as it was in the initial commit dbb805f448f4ee70f2b ( https://github.com/yahoo/pure/blob/dbb805f448f4ee70f2bc0d42979adde5a8bdf649/LICENSE.md )

**Comment by okuryu** [comment]
:+1:

**Comment by redonkulus** [comment]
:+1:

**Comment by jiangbai333** [comment]
merge

**Pull request merged**
