### PR TITLE
Replace button gradients with a subtle highlight.

### PR DESCRIPTION
**Pull request by sethlivingston**
Replaced the button gradient effect with a subtle highlight effect accomplished simply by setting the opacity to 0.90 on hover and focus.

I followed the guidelines for contributing and gave the buttons a run-through on the manual buttons test page.

### CODE REVIEW

**Comment by jamesalley** [comment]
This could be a good PR since IE8 does not support the gradient solution. Could you sign the CLA and revisit this PR? In particular we should remove the special highlight for IE8 if we go with this default styling instead.

**Comment by sethlivingston** [comment]
Hi James,
Yes, I will do that right away...

Date: Mon, 2 Feb 2015 14:13:50 -0800

**Comment by sethlivingston** [comment]
I signed the CLA back in Sep 2014... not sure why it's failing?

You previously signed this CLA on:
Tue Sep 16 2014 21:55:34 GMT+0000 (UTC)
From: 216.110.50.18

**Comment by sethlivingston** [comment]
Also, I'd like to replace this PR with a solution based on the second answer on this SO question:

http://stackoverflow.com/questions/806000/transparent-background-but-not-the-content-text-images-inside-it-in-css-on

This PR makes the entire button semi-transparent, but we don't want the text or any images to be transparent. Can you give me a day or so to submit a better PR based on the solution above?

**Comment by jamesalley** [comment]
Btw for 0.6 I have added a simple border-color for ie8, which wouldn't render the shadow.

**Comment by jamesalley** [comment]
Take your time.

**Comment by yahoocla** [comment]
CLA is valid!

**Pull request closed without merging**
