### PR TITLE
correct spelling for 'usually'

### PR DESCRIPTION
**Pull request by vsopvsop**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by sgryphon** [comment]
Are you serious? You are asking for a valid CLA to fix a (one word) spelling mistake?

I'm pretty sure individual words can't be copyrighted, so I don't think there is any possibility of a legal claim over a one word spelling correction.

**Comment by matthewlynch** [comment]
It's an automatic bot, I don't think it understand the difference between a spelling correction vs a code change

**Comment by vsopvsop** [comment]
@sgryphon Can you do it yourself? I don't want to sign  CLA

**Comment by ericcarraway** [comment]
https://github.com/yahoo/pure/pull/511

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by paazmaya** [comment]
Could the merge button be clicked?

**Pull request merged**
