### PR TITLE
Make .pure-g a true flex-box in firefox

### PR DESCRIPTION
**Pull request by antpaw**
I'm not sure why flex-wrap is important, but as I see it. this change has no downsides and huge benefits.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by antpaw** [comment]
Sorry, now I've discovered the huge downside of this

**Comment by lkraav** [comment]
What was the huge downside?

**Comment by antpaw** [comment]
if you have 3 div with `pure-u-1-2` in chrome this would create 2 lines and each pure-u would be 50% width. As soon as you set `display: flex` firefox starts to display this 3 divs in one line and with 33.3333% width

**Pull request closed without merging**
