### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by kkirsche** [comment]
Signed

**Comment by paazmaya** [comment]
@yahoocla sir?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
Seems reasonable to me. :+1:

**Comment by kkirsche** [comment]
Thanks!

**Pull request merged**
